### ISSUE TITLE
FR-001 "Login page unable to open"

### ISSUE THREAD

**Issue by yogii1981** [Cleerly/issue-tracker#66] opened 2017-12-19 15:33 UTC
## Functional requirement Number : FR001 
As I user, Once I enter my valid username and password, and click enter, so the system should display physician Dashboard.

## Bug :
As I clicked Entered, the page login page refreshed itself and username and Password "textbox" were empty.

### Expected behavior
The system Should display the Physician Dashboard

### Actual behavior
Login Page refreshed itself

### Steps to reproduce the behavior

1. Enter Username
2. Enter password
3. Click "Login"

### Acceptance criteria
1. The system Should display the Physician Dashboard

**Comment by shengt** [comment] 2017-12-19 19:55
@yogii1981 Which environment did you test on?

**Comment by leeight** [comment] 2017-12-20 14:25
@yogii1981 Could not reproduce, which environment are you using?

**Comment by shengt** [comment] 2017-12-26 11:52
Close this one because of the `tested by PM` label

**Closed by shengt** 2017-12-26 11:52 UTC
Labels: bug, Ready for testing, tested by PM, Verfied by the user, Very High
